language: go
go:
  - "1.15"
  - "1.16"
  - "1.17"
  - tip
before_install:
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - goveralls -v -race -service=travis-ci -repotoken=$COVERALLS_TOKEN || go test -race -v
matrix:
  allow_failures:
    - go: tip

